### ISSUE TITLE
🐛 Rome crashing on file deletion during check

### ISSUE THREAD

**Issue by yassere** [romefrontend/rome#949]
Rome used to handle file deletion without crashing, but this is a regression.

## Environment

<details>
<summary>$ rome rage --summary</summary>

```
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Yasser/bin:/Users/Yasser/bin"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
    USER: "Yasser"
  }

User Config
  unset

Rome Version
  0.0.26-dev

Node Version
  14.6.0

Platform
  darwin x64 19.5.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 157
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/Yasser/Dev/rome"
    realCwd: "/Users/Yasser/Dev/rome"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 22_179_840
      pid: 33_931
      uptime: 0.276407927
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 22_179_840
        ownedBytes: 0
        ownedFileCount: 0
        pid: 33_931
        uptime: 0.276242305
      }
    ]
  }
```
</details>

## Steps To Reproduce

Create a file `foo.ts`

Running `./rome check` then deleting `foo.ts` while Rome is linting results in:
<details>
<summary>Error</summary>

```
internal/core/server/fs/MemoryFileSystem.ts:568:9 internalError/request  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ /Users/Yasser/Dev/rome/foo.ts: Not found in memory file system

   4. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.getFileStatsAssert (internal/core/server/fs/MemoryFileSystem.ts:568:9)
        566 │     if (stats === undefined) {
        567 │       throw new FileNotFound(path, "Not found in memory file system");
      > 568 │     }
            │            ^
        569 │     return stats;
        570 │   }
   5. ___R$project$rome$$internal$core$server$WorkerManager_ts$default.getNextWorker (internal/core/server/WorkerManager.ts:371:20)
        370 │       stats = memoryFs.getFileStatsAssert(path);
      > 371 │     }
            │                       ^
        372 │ 
        373 │     // Verify that this file doesn't exceed any size limit
   6. global.runMicrotasks
   7. process.processTicksAndRejections (internal/process/task_queues.js:93:4)
   8. ___R$project$rome$$internal$core$server$fs$FileAllocator_ts$default.assignOwner (internal/core/server/fs/FileAllocator.ts:174:18)
   9. <anonymous> (internal/core/server/WorkerQueue.ts:48:5)
  10. Function.all
  11. ___R$project$rome$$internal$core$server$WorkerQueue_ts$default.prepare (internal/core/server/WorkerQueue.ts:44:2)
  12. ___R$project$rome$$internal$core$server$dependencies$DependencyGraph_ts$default.seed (internal/core/server/dependencies/DependencyGraph.ts:188:2)
  13. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.runGraph (internal/core/server/linter/Linter.ts:293:2)
  14. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.run (internal/core/server/linter/Linter.ts:440:35)
  15. <anonymous> (internal/core/server/linter/Linter.ts:532:19)
  16. _flush (internal/core/server/fs/glob.ts:412:2)
  17. flush (internal/core/server/fs/glob.ts:403:2)
  18. ___R$project$rome$$internal$core$server$fs$glob_ts$watchFilesFromArgs (internal/core/server/fs/glob.ts:480:1)
  19. ___R$project$rome$$internal$core$server$linter$Linter_ts$default.runSingle (internal/core/server/linter/Linter.ts:593:21)
  20. ___R$project$rome$$internal$core$server$linter$Linter_ts$default.throwSingle (internal/core/server/linter/Linter.ts:631:20)
  21. Object.callback (internal/core/server/commands/check.ts:130:3)
  22. ___R$project$rome$$internal$core$server$Server_ts$default.dispatchRequest (internal/core/server/Server.ts:927:4)
  23. ___R$project$rome$$internal$core$server$Server_ts$default.handleRequest (internal/core/server/Server.ts:784:46)
  and 3 others...

  ℹ This diagnostic was derived from an internal Rome error. Potential bug, please report if necessary.
```
</details>

Also, running `./rome check --watch` then deleting `foo.ts` after completing the initial check results in:

<details>
<summary>Error</summary>

```
server project-rome/@internal/core/server/fs/MemoryFileSystem.ts:568:9 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ /Users/Yasser/Dev/rome/foo.ts: Not found in memory file system

   1. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.getFileStatsAssert (
      project-rome/@internal/core/server/fs/MemoryFileSystem.ts:568:9)
   2. ___R$project$rome$$internal$core$server$WorkerManager_ts$default.getNextWorker (project-rome/@internal/core/server/WorkerManager.ts:371:20)
   3. ___R$project$rome$$internal$core$server$fs$FileAllocator_ts$default.assignOwner (project-rome/@internal/core/server/fs/FileAllocator.ts:174:18)
   4. <anonymous> (project-rome/@internal/core/server/WorkerQueue.ts:48:5)
   5. Function.all
   6. ___R$project$rome$$internal$core$server$WorkerQueue_ts$default.prepare (project-rome/@internal/core/server/WorkerQueue.ts:44:2)
   7. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.runLint (project-rome/@internal/core/server/linter/Linter.ts:189:2)
   8. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.run (project-rome/@internal/core/server/linter/Linter.ts:439:23)
   9. <anonymous> (project-rome/@internal/core/server/linter/Linter.ts:532:19)
  10. _flush (project-rome/@internal/core/server/fs/glob.ts:412:2)
  11. flush (project-rome/@internal/core/server/fs/glob.ts:403:2)

  ℹ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.
```
</details>

## Expected Results

Rome should not crash.

**Comment by sebmck** [comment]
Fixed by #953 with a regression test.

**Comment by yassere** [comment]
@sebmck I'm getting a different error now.

Deleting `foo.ts` during `./rome check --watch` results in:

<details>
<summary>Error</summary>

```
server project-rome/@internal/core/server/fs/MemoryFileSystem.ts:573:9 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ /Users/Yasser/Dev/rome/foo.ts: Not found in memory file system

  1. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.getFileStatsAssert (
     project-rome/@internal/core/server/fs/MemoryFileSystem.ts:573:9)
  2. ___R$project$rome$$internal$core$server$WorkerManager_ts$default.getNextWorker (project-rome/@internal/core/server/WorkerManager.ts:371:20)
  3. ___R$project$rome$$internal$core$server$fs$FileAllocator_ts$default.assignOwner (project-rome/@internal/core/server/fs/FileAllocator.ts:179:18)
  4. ___R$project$rome$$internal$core$server$WorkerQueue_ts$default.pushQueue (project-rome/@internal/core/server/WorkerQueue.ts:73:26)
  5. ___R$project$rome$$internal$core$server$dependencies$DependencyGraph_ts$default.seed (
     project-rome/@internal/core/server/dependencies/DependencyGraph.ts:230:3)
  6. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.runGraph (project-rome/@internal/core/server/linter/Linter.ts:282:2)
  7. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.run (project-rome/@internal/core/server/linter/Linter.ts:438:35)
  8. ___R$$priv$project$rome$$internal$core$server$fs$glob_ts$GlobberWatcher.callback (project-rome/@internal/core/server/linter/Linter.ts:532:18)
  9. ___R$$priv$project$rome$$internal$core$server$fs$glob_ts$GlobberWatcher.flush (project-rome/@internal/core/server/fs/glob.ts:245:3)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

(node:47615) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(Use `node --trace-warnings ...` to show where the warning was created)
 worker 1 project-rome/@internal/core/server/WorkerManager.ts:325:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:325:5)
  2. Object.onceWrapper (events.js:421:25)
  3. ChildProcess.emit (events.js:314:19)
  4. Process.onexit (internal/child_process.js:276:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

 worker 2 project-rome/@internal/core/server/WorkerManager.ts:325:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:325:5)
  2. Object.onceWrapper (events.js:421:25)
  3. ChildProcess.emit (events.js:314:19)
  4. Process.onexit (internal/child_process.js:276:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

 worker 3 project-rome/@internal/core/server/WorkerManager.ts:325:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:325:5)
  2. Object.onceWrapper (events.js:421:25)
  3. ChildProcess.emit (events.js:314:19)
  4. Process.onexit (internal/child_process.js:276:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

 worker 4 project-rome/@internal/core/server/WorkerManager.ts:325:5 internalError/fatal  INTERNAL   FATAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Process unexpectedly exit

  1. ChildProcess.<anonymous> (project-rome/@internal/core/server/WorkerManager.ts:325:5)
  2. Object.onceWrapper (events.js:421:25)
  3. ChildProcess.emit (events.js:314:19)
  4. Process.onexit (internal/child_process.js:276:11)

  ⚠ Rome exited as this error could not be handled and resulted in a fatal error. Please report if necessary.

 Analyzing changed files                                                                                                                        elapsed 17s 
```

**Comment by yassere** [comment]
I'm also still getting an error when deleting a file during `./rome check`:

<details>
<summary>Error</summary>

```
 internal/core/server/fs/MemoryFileSystem.ts:573:9 internalError/request  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ /Users/Yasser/Dev/rome/foo.ts: Not found in memory file system

   2. ___R$project$rome$$internal$core$server$fs$MemoryFileSystem_ts$default.getFileStatsAssert (internal/core/server/fs/MemoryFileSystem.ts:573:9)
        571 │     if (stats === undefined) {
        572 │       throw new FileNotFound(path, "Not found in memory file system");
      > 573 │     }
            │            ^
        574 │     return stats;
        575 │   }
   3. ___R$project$rome$$internal$core$server$WorkerManager_ts$default.getNextWorker (internal/core/server/WorkerManager.ts:371:20)
        370 │       stats = memoryFs.getFileStatsAssert(path);
      > 371 │     }
            │                       ^
        372 │ 
        373 │     // Verify that this file doesn't exceed any size limit
   4. global.runMicrotasks
   5. process.processTicksAndRejections (internal/process/task_queues.js:93:4)
   6. ___R$project$rome$$internal$core$server$fs$FileAllocator_ts$default.assignOwner (internal/core/server/fs/FileAllocator.ts:179:18)
   7. ___R$project$rome$$internal$core$server$WorkerQueue_ts$default.pushQueue (internal/core/server/WorkerQueue.ts:73:26)
   8. ___R$project$rome$$internal$core$server$dependencies$DependencyGraph_ts$default.seed (internal/core/server/dependencies/DependencyGraph.ts:230:3)
   9. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.runGraph (internal/core/server/linter/Linter.ts:282:2)
  10. ___R$$priv$project$rome$$internal$core$server$linter$Linter_ts$LintRunner.run (internal/core/server/linter/Linter.ts:438:35)
  11. ___R$$priv$project$rome$$internal$core$server$fs$glob_ts$GlobberWatcher.callback (internal/core/server/linter/Linter.ts:532:18)
  12. ___R$$priv$project$rome$$internal$core$server$fs$glob_ts$GlobberWatcher.flush (internal/core/server/fs/glob.ts:245:3)
  13. ___R$$priv$project$rome$$internal$core$server$fs$glob_ts$GlobberWatcher.init (internal/core/server/fs/glob.ts:299:2)
  14. ___R$project$rome$$internal$core$server$fs$glob_ts$Globber.watch (internal/core/server/fs/glob.ts:165:14)
  15. ___R$project$rome$$internal$core$server$linter$Linter_ts$default.runSingle (internal/core/server/linter/Linter.ts:592:21)
  16. ___R$project$rome$$internal$core$server$linter$Linter_ts$default.throwSingle (internal/core/server/linter/Linter.ts:630:20)
  17. Object.callback (internal/core/server/commands/check.ts:130:3)
  18. ___R$project$rome$$internal$core$server$Server_ts$default.dispatchRequest (internal/core/server/Server.ts:926:4)
  19. ___R$project$rome$$internal$core$server$Server_ts$default.handleRequest (internal/core/server/Server.ts:783:46)
  20. <anonymous> (internal/core/server/Server.ts:601:10)
  21. Function.all
  and 1 others...

  ⚠ This diagnostic was derived from an internal Rome error. Potential bug, please report if necessary.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
</details>

**Comment by sebmck** [comment]
Hopefully fixed again by #957.
